package Persistencia;

import Util.DataUtility;
import java.util.Date;

public class BuildDeTabelas extends ConexaoComOBancoDeDados {

    private final String tabelaPerfil = "CREATE TABLE IF NOT EXISTS PERFIL ("
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 101, INCREMENT BY 1) ,"
            + "DESCRICAO VARCHAR(100) NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR));";

    private final String tabelaEstado = "CREATE TABLE IF NOT EXISTS ESTADO ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) ,"
            + "DESCRICAO VARCHAR(100) NOT NULL,"
            + "SIGLA VARCHAR(3) NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR));";

    private final String tabelaCidade = "CREATE TABLE IF NOT EXISTS CIDADE ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) ,"
            + "DESCRICAO VARCHAR(100) NOT NULL,"
            + "IDENTIFICADOR_ESTADO INTEGER NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_ESTADO) REFERENCES ESTADO(IDENTIFICADOR));";

    private final String tabelaBairro = "CREATE TABLE IF NOT EXISTS BAIRRO ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) ,"
            + "DESCRICAO VARCHAR(100) NOT NULL,"
            + "IDENTIFICADOR_CIDADE INTEGER NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_CIDADE) REFERENCES CIDADE(IDENTIFICADOR));";

    private final String tabelaLogradouro = "CREATE TABLE IF NOT EXISTS LOGRADOURO ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) ,"
            + "DESCRICAO VARCHAR(100) NOT NULL,"
            + "IDENTIFICADOR_BAIRRO INTEGER NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_BAIRRO) REFERENCES BAIRRO(IDENTIFICADOR));";

    private final String tabelaCep = "CREATE TABLE IF NOT EXISTS CEP ( "
            + "CEP INTEGER NOT NULL ,"
            + "IDENTIFICADOR_LOGRADOURO INTEGER NOT NULL, "
            + "PRIMARY KEY(CEP), "
            + "FOREIGN KEY(IDENTIFICADOR_LOGRADOURO) REFERENCES LOGRADOURO(IDENTIFICADOR));";

    private final String tabelaTipoEndereco = "CREATE TABLE IF NOT EXISTS TIPO_ENDERECO ("
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) ,"
            + "DESCRICAO VARCHAR(100) NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR));";

    private final String tabelaEndereco = "CREATE TABLE IF NOT EXISTS ENDERECO ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 101, INCREMENT BY 1) ,"
            + "CEP_CEP INTEGER NOT NULL, "
            + "COMPLEMENTO VARCHAR(100) NOT NULL, "
            + "NUMERO INTEGER NOT NULL, "
            + "IDENTIFICADOR_TIPO_ENDERECO INTEGER NOT NULL,  "
            + "PONTO_REFERENCIA VARCHAR(100) NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY(CEP_CEP) REFERENCES CEP(CEP), "
            + "FOREIGN KEY(IDENTIFICADOR_TIPO_ENDERECO) REFERENCES TIPO_ENDERECO(IDENTIFICADOR));";

    private final String tabelaTipoTelefone = "CREATE TABLE IF NOT EXISTS TIPO_TELEFONE ("
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) ,"
            + "DESCRICAO VARCHAR(50) NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR));";

    private final String tabelaTelefone = "CREATE TABLE IF NOT EXISTS TELEFONE ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) ,"
            + "DDD INTEGER NOT NULL, "
            + "NUMERO VARCHAR(20) NOT NULL, "
            + "IDENTIFICADOR_TIPO_TELEFONE INTEGER NOT NULL,  "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_TIPO_TELEFONE) REFERENCES TIPO_TELEFONE(IDENTIFICADOR));";

    private final String tabelaCargo = "CREATE TABLE IF NOT EXISTS CARGO ("
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 101, INCREMENT BY 1) ,"
            + "DESCRICAO VARCHAR(50) NOT NULL, "
            + "ATIVO BOOLEAN DEFAULT TRUE NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR));";

    private final String tabelaUsuario = "CREATE TABLE IF NOT EXISTS USUARIO ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 101, INCREMENT BY 1) ,"
            + "NOME VARCHAR(100) NOT NULL, "
            + "CPF_CNPJ VARCHAR(20) NOT NULL, "
            + "SEXO VARCHAR(1) NOT NULL, "
            + "DATA_NASCIMENTO DATE NOT NULL, "
            + "USERNAME VARCHAR(20) NOT NULL, "
            + "SENHA VARCHAR(150) NOT NULL, "
            + "ATIVO BOOLEAN DEFAULT TRUE NOT NULL, "
            + "IDENTIFICADOR_PERFIL INTEGER NOT NULL, "
            + "DATA_CADASTRO DATE NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_PERFIL) REFERENCES PERFIL(IDENTIFICADOR));";

    /*
    Tabela USUARIO_TELEFONE REPRESENTA A TABELA ASSOCIATIVA DO RELACIONAMENTO DE 
    MUITOS PARA MUITOS  ENTRE USUARIO E TELEFONE ...UM USUÁRIO TEM UMA LISTA DE
    TELEFONE --> List<Telefone> listaTelefone. 
     */
    private final String tabelaUsuarioTelefone = "CREATE TABLE IF NOT EXISTS USUARIO_TELEFONE ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) ,"
            + "IDENTIFICADOR_USUARIO INTEGER NOT NULL, "
            + "IDENTIFICADOR_TELEFONE INTEGER NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_USUARIO) REFERENCES USUARIO(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_TELEFONE) REFERENCES TELEFONE(IDENTIFICADOR));";

    /*
    Tabela USUARIO_ENDEREÇO REPRESENTA A TABELA ASSOCIATIVA DO RELACIONAMENTO DE 
    MUITOS PARA MUITOS  ENTRE USUARIO E ENDEREÇO ...UM USUÁRIO TEM UMA LISTA DE
    ENDEREÇOS --> List<Endereco> listaEndereco. 
     */
    private final String tabelaUsuarioEndereco = "CREATE TABLE IF NOT EXISTS USUARIO_ENDERECO ( "
            + "IDENTIFICADOR INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) ,"
            + "IDENTIFICADOR_USUARIO INTEGER NOT NULL, "
            + "IDENTIFICADOR_ENDERECO INTEGER NOT NULL, "
            + "PRIMARY KEY(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_USUARIO) REFERENCES USUARIO(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_ENDERECO) REFERENCES ENDERECO(IDENTIFICADOR));";

    private final String tabelaFuncionario = "CREATE TABLE IF NOT EXISTS FUNCIONARIO ( "
            + "MATRICULA INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1000, INCREMENT BY 10) ,"
            + "IDENTIFICADOR_CARGO INTEGER NOT NULL, "
            + "DATA_ADMISSAO DATE NOT NULL, "
            + "IDENTIFICADOR_USUARIO INTEGER NOT NULL, "
            + "DATA_DESLIGAMENTO DATE, "
            + "PRIMARY KEY(MATRICULA), "
            + "FOREIGN KEY(IDENTIFICADOR_CARGO) REFERENCES CARGO(IDENTIFICADOR), "
            + "FOREIGN KEY(IDENTIFICADOR_USUARIO) REFERENCES USUARIO(IDENTIFICADOR));";

    /*
    AQUI COMEÇA OS SCRIPT´S SQL DE INSERÇÃO DOS DADOS INICIAIS
     */
    private final String dadosIniciaisPerfil = "INSERT INTO PERFIL "
            + "(DESCRICAO) VALUES"
            + "('ADMINISTRADOR'),"
            + "('DIRETOR'),"
            + "('ATENDENTE');";

    private final String dadosIniciaisEstado = "INSERT INTO ESTADO "
            + "(DESCRICAO, SIGLA) VALUES "
            + "('Acre','AC'),"
            + "('Alagoas','AL'),"
            + "('Amapá','AP'),"
            + "('Amazonas','AM'),"
            + "('Bahia','BA'),"
            + "('Ceará','CE'),"
            + "('Espírito Santo','ES'),"
            + "('Goiás','GO'),"
            + "('Maranhão','MA'),"
            + "('Mato Grosso','MT'),"
            + "('Mato Grosso do Sul','MS'),"
            + "('Minas Gerais','MG'),"
            + "('Pará','PA'),"
            + "('Paraíba','PB'),"
            + "('Paraná','PR'),"
            + "('Pernambuco','PE'),"
            + "('Piauí','PI'),"
            + "('Rio de Janeiro','RJ'),"
            + "('Rio Grande do Norte','RN'),"
            + "('Rio Grande do Sul','RS'),"
            + "('Rondônia','RO'),"
            + "('Roraima','RR'),"
            + "('Santa Catarina','SC'),"
            + "('São Paulo','SP'),"
            + "('Sergipe','SE'),"
            + "('Tocantins','TO'),"
            + "('Distrito Federal','DF');";

    private final String dadosIniciaisCidade = "INSERT INTO CIDADE "
            + "(DESCRICAO, IDENTIFICADOR_ESTADO) VALUES  "
            + "('Brasilia', 27 ),"
            + "('Aguas Lindas', 8 ),"
            + "('Novo Gama', 8 ); ";

    private final String dadosIniciaisBairro = "INSERT INTO BAIRRO "
            + "(DESCRICAO, IDENTIFICADOR_CIDADE) VALUES  "
            + "('Gama', 1 ),"
            + "('Taguatinga', 1 ),"
            + "('Brazlandia', 1 ),"
            + "('Sobradinho', 1 ),"
            + "('Planaltina', 1 ),"
            + "('Paranoa', 1 ),"
            + "('Nucleo Bandeirante', 1 ),"
            + "('Ceilandia', 1 ),"
            + "('Guara', 1 ),"
            + "('Cruzeiro', 1 ),"
            + "('Samambaia', 1 ),"
            + "('Santa Maria', 1 ),"
            + "('São Sebastião', 1 ),"
            + "('Recanto das Emas', 1 ),"
            + "('Lago Sul', 1 ),"
            + "('Riacho Fundo', 1 ),"
            + "('Lago Norte', 1 ),"
            + "('Candangolandia', 1 ),"
            + "('Aguas Claras', 1 ),"
            + "('Riacho Fundo II', 1 ),"
            + "('Sudoeste', 1 ),"
            + "('Varjao', 1 ),"
            + "('Park Way', 1 ),"
            + "('Jardim Botanico', 1 ),"
            + "('Vicente Pires', 1 ),"
            + "('Fercal', 1 ),"
            + "('Arapoanga', 1 ),"
            + "('Estrutural', 1 ),"
            + "('Arniqueira', 1 ),"
            + "('Octogonal', 1 ),"
            + "('Noroeste', 1 ),"
            + "('Jardins Mangueiral', 1 );";

    private final String dadosIniciaisLogradouro = "INSERT INTO LOGRADOURO "
            + "(DESCRICAO, IDENTIFICADOR_BAIRRO) VALUES  "
            + "('AC 200', 12 ),"
            + "('AC 200 Bloco A', 12 ),"
            + "('AC 200 Bloco B', 12 ),"
            + "('AC 200 Bloco C', 12 ),"
            + "('AC 200 Bloco D', 12 ),"
            + "('AC 200 Bloco E', 12 ),"
            + "('AC 200 Bloco F', 12 ),"
            + "('AC 200 Bloco G', 12 ),"
            + "('AC 200 Bloco H', 12 ),"
            + "('AC 300', 12 ),"
            + "('AC 300 Bloco A', 12 ),"
            + "('AC 300 Bloco B', 12 ),"
            + "('AC 300 Bloco C', 12 ),"
            + "('AC 300 Bloco D', 12 ),"
            + "('AC 300 Bloco E', 12 ),"
            + "('AC 300 Bloco F', 12 ),"
            + "('AC 300 Bloco G', 12 ),"
            + "('QR 100', 12 ),"
            + "('QR 100 Conjunto A', 12 ),"
            + "('QR 100 Conjunto A-1', 12 ),"
            + "('QR 100 Conjunto B', 12 ),"
            + "('QR 100 Conjunto B-1', 12 ),"
            + "('QR 100 Conjunto C', 12 ),"
            + "('QR 100 Conjunto C-1', 12 ),"
            + "('QR 100 Conjunto D', 12 ),"
            + "('QR 100 Conjunto E', 12 ),"
            + "('QR 100 Conjunto F', 12 ),"
            + "('QR 100 Conjunto G', 12 ),"
            + "('QR 100 Conjunto H', 12 ),"
            + "('QR 100 Conjunto H-1', 12 ),"
            + "('QR 100 Conjunto I', 12 ),"
            + "('QR 100 Conjunto I-1', 12 ),"
            + "('QR 100 Conjunto J', 12 ),"
            + "('QR 100 Conjunto J-1', 12 ),"
            + "('QR 100 Conjunto K', 12 ),"
            + "('QR 100 Conjunto L', 12 ),"
            + "('QR 100 Conjunto M', 12 ),"
            + "('QR 100 Conjunto N', 12 ),"
            + "('QR 100 Conjunto N-1', 12 ),"
            + "('QR 100 Conjunto O', 12 ),"
            + "('QR 100 Conjunto P', 12 ),"
            + "('QR 100 Conjunto Q', 12 ),"
            + "('QR 100 Conjunto Q-1', 12 ),"
            + "('QR 100 Conjunto R', 12 ),"
            + "('QR 100 Conjunto S', 12 ),"
            + "('QR 100 Conjunto T', 12 ),"
            + "('QR 100 Conjunto T-1', 12 ),"
            + "('QR 100 Conjunto U', 12 ),"
            + "('QR 100 Conjunto V', 12 ),"
            + "('QR 100 Conjunto W', 12 ),"
            + "('QR 100 Conjunto X', 12 ),"
            + "('QR 100 Conjunto X-1', 12 ),"
            + "('QR 100 Conjunto Y', 12 );";

    private final String dadosIniciaisCEP = "INSERT INTO CEP "
            + "(CEP, IDENTIFICADOR_LOGRADOURO) VALUES  "
            + "(72500103, 1 ),"
            + "(72500104, 2 ),"
            + "(72500105, 3 ),"
            + "(72500106, 4 ),"
            + "(72500107, 5 ),"
            + "(72500108, 6 ),"
            + "(72500120, 7 ),"
            + "(72500121, 8 ),"
            + "(72500122, 9 ),"
            + "(72500123, 10 ),"
            + "(72500124, 11 ),"
            + "(72500125, 12 ),"
            + "(72500126, 13 ),"
            + "(72500127, 14 ),"
            + "(72500400, 15 ),"
            + "(72500401, 16 ),"
            + "(72500402, 17 ),"
            + "(72500403, 18 ),"
            + "(72500404, 19 ),"
            + "(72500405, 20 ),"
            + "(72500406, 21 ),"
            + "(72500407, 22 ),"
            + "(72500408, 23 ),"
            + "(72500409, 24 ),"
            + "(72500410, 25 ),"
            + "(72500411, 26 ),"
            + "(72500412, 27 ),"
            + "(72500413, 28 ),"
            + "(72500414, 29 ),"
            + "(72500415, 30 ),"
            + "(72500416, 31 ),"
            + "(72500417, 32 ),"
            + "(72500418, 33 ),"
            + "(72500419, 34 ),"
            + "(72500420, 35 ),"
            + "(72500421, 36 ),"
            + "(72500422, 37 ),"
            + "(72500423, 38 ),"
            + "(72500424, 39 ),"
            + "(72500425, 40 ),"
            + "(72500426, 41 ),"
            + "(72500427, 42 ),"
            + "(72500428, 43 ),"
            + "(72500429, 44 ),"
            + "(72500430, 45 ),"
            + "(72500431, 46 ),"
            + "(72500432, 47 ),"
            + "(72500433, 48 ),"
            + "(72500434, 49 ),"
            + "(72500435, 50 ),"
            + "(72500436, 51 ),"
            + "(72501100, 52 ),"
            + "(72501101, 53 );";

    private final String dadosIniciaisTipoEndereco = "INSERT INTO TIPO_ENDERECO "
            + "(DESCRICAO) VALUES"
            + "('aeroporto'),"
            + "('alameda'),"
            + "('área'),"
            + "('avenida'),"
            + "('campo'),"
            + "('chácara'),"
            + "('colônia'),"
            + "('comercial'),"
            + "('condomínio'),"
            + "('conjunto'),"
            + "('distrito'),"
            + "('esplanada'),"
            + "('estação'),"
            + "('estrada'),"
            + "('favela'),"
            + "('fazenda'),"
            + "('feira'),"
            + "('jardim'),"
            + "('ladeira'),"
            + "('lago'),"
            + "('lagoa'),"
            + "('largo'),"
            + "('loteamento'),"
            + "('morro'),"
            + "('núcleo'),"
            + "('parque'),"
            + "('passarela'),"
            + "('pátio'),"
            + "('praça'),"
            + "('quadra'),"
            + "('recanto'),"
            + "('residencial'),"
            + "('rodovia'),"
            + "('rua'),"
            + "('setor'),"
            + "('sítio'),"
            + "('travessa'),"
            + "('trecho'),"
            + "('trevo'),"
            + "('vale'),"
            + "('vereda'),"
            + "('via'),"
            + "('viaduto'),"
            + "('viela'),"
            + "('vila');";

    private final String dadosIniciaisEndereco = "INSERT INTO ENDERECO "
            + "(CEP_CEP, COMPLEMENTO, NUMERO, IDENTIFICADOR_TIPO_ENDERECO, PONTO_REFERENCIA) VALUES"
            + "(72500400,'APARTAMENTO',103,32,'Quadra ao lado da Escola Técnica de Brasília'),"
            + "(72500432,'CASA',8,34,'Em frente ao Pão de Açucar');";

    private final String dadosIniciaisTipoTelefone = "INSERT INTO TIPO_TELEFONE "
            + "(DESCRICAO) VALUES"
            + "('CELULAR'),"
            + "('RESIDENCIAL'),"
            + "('COMERCIAL');";

    private final String dadosIniciaisTelefone = "INSERT INTO TELEFONE "
            + "(DDD,NUMERO, IDENTIFICADOR_TIPO_TELEFONE) VALUES"
            + "(061,'998565878',1),"
            + "(061,'080065788',3),"
            + "(061,'34567890',2);";

    private final String dadosIniciaisUsuario = "INSERT INTO USUARIO "
            + "(NOME, CPF_CNPJ, SEXO, DATA_NASCIMENTO, USERNAME, SENHA, ATIVO, IDENTIFICADOR_PERFIL, DATA_CADASTRO) VALUES "
            + "('Ana Paula Loiola De Jesus Peres','01828445100','F','1978-08-16','paula.pljp','123',true,103,'" + DataUtility.formatarDataComPadrao(new Date(), "yyyy-MM-dd") + "'),"
            + "('Ivan Oliveira','0486945578','M','1978-08-16','ivan10br','123',true,101,'" + DataUtility.formatarDataComPadrao(new Date(), "yyyy-MM-dd") + "');";

    private final String dadosIniciaisUsuarioTelefone = "INSERT INTO USUARIO_TELEFONE "
            + "(IDENTIFICADOR_USUARIO, IDENTIFICADOR_TELEFONE) VALUES"
            + "(101,2),"
            + "(102,3),"
            + "(102,1);";

    private final String dadosIniciaisUsuarioEndereco = "INSERT INTO USUARIO_ENDERECO "
            + "(IDENTIFICADOR_USUARIO, IDENTIFICADOR_ENDERECO) VALUES "
            + "(101,101),"
            + "(102,102);";

    private final String dadosIniciaisCargo = "INSERT INTO CARGO "
            + "(DESCRICAO, ATIVO) VALUES "
            + "('Analista de desenvolvimento de sistemas',true),"
            + "('Engenheiro de Software',true),"
            + "('Técnico em informática',true),"
            + "('Gerente de ambulatório',true),"
            + "('Professor',true),"
            + "('Estagiário',true);";

    private final String dadosIniciaisFuncionario = "INSERT INTO FUNCIONARIO "
            + "(IDENTIFICADOR_CARGO, DATA_ADMISSAO, IDENTIFICADOR_USUARIO, DATA_DESLIGAMENTO) VALUES "
            + "(101,'2021-12-05',101,NULL),"
            + "(105,'2021-12-05',102,NULL);";

    public void construirTabelas() {

        /*
        A ordem de criar as tabelas deve observar as
        dependências entre elas
         */
        executarScriptSql(tabelaPerfil);
        executarScriptSql(tabelaEstado);
        executarScriptSql(tabelaCidade);
        executarScriptSql(tabelaBairro);
        executarScriptSql(tabelaLogradouro);
        executarScriptSql(tabelaCep);
        executarScriptSql(tabelaTipoEndereco);
        executarScriptSql(tabelaEndereco);
        executarScriptSql(tabelaTipoTelefone);
        executarScriptSql(tabelaTelefone);
        executarScriptSql(tabelaCargo);
        executarScriptSql(tabelaUsuario);
        executarScriptSql(tabelaUsuarioTelefone);
        executarScriptSql(tabelaUsuarioEndereco);
        executarScriptSql(tabelaFuncionario);
    }

    public void inserirDadosIniciais() {

        if (iSTabelaVazia("PERFIL")) {
            executarScriptSql(dadosIniciaisPerfil);
        }

        if (iSTabelaVazia("ESTADO")) {
            executarScriptSql(dadosIniciaisEstado);
        }

        if (iSTabelaVazia("CIDADE")) {
            executarScriptSql(dadosIniciaisCidade);
        }
        if (iSTabelaVazia("BAIRRO")) {
            executarScriptSql(dadosIniciaisBairro);
        }
        if (iSTabelaVazia("LOGRADOURO")) {
            executarScriptSql(dadosIniciaisLogradouro);
        }

        if (iSTabelaVazia("CEP")) {
            executarScriptSql(dadosIniciaisCEP);
        }
        if (iSTabelaVazia("TIPO_ENDERECO")) {
            executarScriptSql(dadosIniciaisTipoEndereco);
        }

        if (iSTabelaVazia("ENDERECO")) {
            executarScriptSql(dadosIniciaisEndereco);
        }

        if (iSTabelaVazia("TIPO_TELEFONE")) {
            executarScriptSql(dadosIniciaisTipoTelefone);
        }

        if (iSTabelaVazia("TELEFONE")) {
            executarScriptSql(dadosIniciaisTelefone);
        }

        if (iSTabelaVazia("USUARIO")) {
            executarScriptSql(dadosIniciaisUsuario);
        }

        if (iSTabelaVazia("USUARIO_TELEFONE")) {
            executarScriptSql(dadosIniciaisUsuarioTelefone);
        }

        if (iSTabelaVazia("USUARIO_ENDERECO")) {
            executarScriptSql(dadosIniciaisUsuarioEndereco);
        }

        if (iSTabelaVazia("CARGO")) {
            executarScriptSql(dadosIniciaisCargo);
        }

        if (iSTabelaVazia("FUNCIONARIO")) {
            executarScriptSql(dadosIniciaisFuncionario);
        }

    }

}
